### ISSUE TITLE
Approvazione prima versione Project Plan

### ISSUE THREAD

**Issue by RaphacePrime** [RaphacePrime/ProgettoIngegneriaDelSoftware#6]
Percorso project plan: ProgettoIngegneriaDelSoftware/Documenti/ProjectPlan_vers1.pdf

**Comment by garganti** [comment]
Approvo con alcune osservazioni
- parlate di team agile ma poi il modello è a cascata. Va bene ma non fate confusione
- su Standard, linee guida, procedure potete fare riferimento allo standard Java
- la deadline del  13/01/2025  è solo indicativa
